import {
  siC,
  siClaude,
  siClickup,
  siConfluence,
  siCplusplus,
  siFigma,
  siFramer,
  siGithub,
  siHtml5,
  siJavascript,
  siJira,
  siMiro,
  siModelcontextprotocol,
  siNextdotjs,
  siNotion,
  siOpenjdk,
  siPostgresql,
  siPython,
  siR,
  siReact,
  siSnowflake,
  siSupabase,
  siTypescript,
  siVercel,
  siVite,
  type SimpleIcon,
} from "simple-icons";

// Brand icons come from Simple Icons (CC0). Some brands (Amplitude, Tableau, Adobe, OpenAI,
// MATLAB, ...) have asked Simple Icons not to carry their logos, so those show as text only.
export type Skill = { name: string; icon?: SimpleIcon };
export type SkillGroup = { title: string; items: Skill[] };

export const skillsIntro = "The whole toolbox.";

export const skillGroups: SkillGroup[] = [
  {
    title: "Product",
    items: [
      { name: "Roadmapping" },
      { name: "User Research" },
      { name: "Data Analysis" },
      { name: "A/B Testing & Experimentation" },
      { name: "UI/UX" },
      { name: "Agile/Scrum" },
      { name: "PRDs" },
      { name: "User Interviews" },
      { name: "Competitive Analysis" },
      { name: "UAT" },
    ],
  },
  {
    title: "AI",
    items: [
      { name: "Claude", icon: siClaude },
      { name: "Claude Code", icon: siClaude },
      { name: "MCP", icon: siModelcontextprotocol },
      { name: "OpenAI API" },
      { name: "Prompt Engineering" },
      { name: "LLM Integration" },
      { name: "AI Automation" },
      { name: "Agentic Workflows" },
      { name: "AI Enablement & Training" },
    ],
  },
  {
    title: "Tools",
    items: [
      { name: "Figma", icon: siFigma },
      { name: "Framer", icon: siFramer },
      { name: "Notion", icon: siNotion },
      { name: "Miro", icon: siMiro },
      { name: "Jira", icon: siJira },
      { name: "Confluence", icon: siConfluence },
      { name: "ClickUp", icon: siClickup },
      { name: "Vercel", icon: siVercel },
      { name: "Salesforce" },
      { name: "Amplitude" },
      { name: "Heap" },
      { name: "UserTesting" },
      { name: "Tableau" },
      { name: "Adobe CC" },
    ],
  },
  {
    title: "Stack",
    items: [
      { name: "Python", icon: siPython },
      { name: "SQL" },
      { name: "TypeScript", icon: siTypescript },
      { name: "JavaScript", icon: siJavascript },
      { name: "React", icon: siReact },
      { name: "Next.js", icon: siNextdotjs },
      { name: "HTML/CSS", icon: siHtml5 },
      { name: "PostgreSQL", icon: siPostgresql },
      { name: "Supabase", icon: siSupabase },
      { name: "Snowflake", icon: siSnowflake },
      { name: "Git/GitHub", icon: siGithub },
      { name: "Vite", icon: siVite },
      { name: "Java", icon: siOpenjdk },
      { name: "R", icon: siR },
      { name: "C", icon: siC },
      { name: "C++", icon: siCplusplus },
      { name: "MATLAB" },
      { name: "Bubble.io" },
    ],
  },
];
